module.exports = {
  apps: [
    {
      name: "canvas-gateway",
      script: "server/dist/index.js",
      interpreter: "node",
      cwd: __dirname,
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        HOST: "0.0.0.0",
        DB_PATH: "./data/canvas.json",
      },
      max_memory_restart: "256M",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "logs/gateway-error.log",
      out_file: "logs/gateway-out.log",
      merge_logs: true,
    },
    {
      name: "canvas-frontend",
      script: "node_modules/.bin/vite",
      args: "preview --host 0.0.0.0 --port 5173",
      interpreter: "none",
      cwd: __dirname + "/apps/web-canvas",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "128M",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 2000,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "../../logs/frontend-error.log",
      out_file: "../../logs/frontend-out.log",
      merge_logs: true,
    },
  ],
};
