/**
 * Hermes / Eva Local Integration Configuration
 *
 * This module generates configuration snippets for connecting
 * Hermes Agent or Eva to the Canvas Workspace Gateway.
 *
 * Topology A: All services run on the same VPS.
 * - Gateway HTTP MCP endpoint: http://localhost:3001/mcp
 * - Gateway SSE endpoint:     http://localhost:3001/sse
 * - Skybridge MCP (stdio):    node apps/skybridge-mcp/dist/server/index.js
 */

export interface HermesMcpServerConfig {
  name: string;
  transport: "http" | "stdio" | "sse";
  url?: string;
  command?: string;
  args?: string[];
  env?: Record<string, string>;
}

export interface HermesConfig {
  mcp_servers: Record<string, HermesMcpServerConfig>;
  canvas_gateway: {
    url: string;
    ws_url: string;
    mcp_http_url: string;
    mcp_sse_url: string;
  };
}

const WORKSPACE_ROOT = process.env.WORKSPACE_ROOT || "/opt/canvas-workspace";
const GATEWAY_HOST = process.env.GATEWAY_HOST || "localhost";
const GATEWAY_PORT = process.env.PORT || "3001";

export function generateHermesConfig(): HermesConfig {
  const baseUrl = `http://${GATEWAY_HOST}:${GATEWAY_PORT}`;

  return {
    mcp_servers: {
      canvas_workspace: {
        name: "canvas_workspace",
        transport: "http",
        url: `${baseUrl}/mcp`,
      },
      skybridge_tools: {
        name: "skybridge_tools",
        transport: "stdio",
        command: "node",
        args: [`${WORKSPACE_ROOT}/apps/skybridge-mcp/dist/server/index.js`],
      },
    },
    canvas_gateway: {
      url: baseUrl,
      ws_url: `ws://${GATEWAY_HOST}:${GATEWAY_PORT}/ws`,
      mcp_http_url: `${baseUrl}/mcp`,
      mcp_sse_url: `${baseUrl}/sse`,
    },
  };
}

/**
 * Generate YAML config snippet for Hermes config.yaml
 */
export function generateYamlConfig(): string {
  const config = generateHermesConfig();
  return `# Canvas Workspace MCP Configuration for Hermes/Eva
# Generated by canvas-core-workspace — Topology A (All-on-VPS)
# Paste this into your Hermes config.yaml

mcp_servers:
  canvas_workspace:
    url: "${config.mcp_servers.canvas_workspace.url}"
    transport: "http"
  skybridge_tools:
    command: "node"
    args: ["${config.mcp_servers.skybridge_tools.args?.[0]}"]

# Canvas Gateway endpoints (for direct API access)
canvas_gateway:
  url: "${config.canvas_gateway.url}"
  ws_url: "${config.canvas_gateway.ws_url}"
  mcp_http_url: "${config.canvas_gateway.mcp_http_url}"
  mcp_sse_url: "${config.canvas_gateway.mcp_sse_url}"
`;
}

/**
 * Generate JSON config snippet for mcp_servers.json
 */
export function generateJsonConfig(): string {
  return JSON.stringify(generateHermesConfig(), null, 2);
}

// CLI: Run directly to print configs
const isMainModule = import.meta.url === `file://${process.argv[1]}`;
if (isMainModule) {
  console.log("=== YAML Config (for config.yaml) ===\n");
  console.log(generateYamlConfig());
  console.log("\n=== JSON Config (for mcp_servers.json) ===\n");
  console.log(generateJsonConfig());
}
