#!/usr/bin/env bash
# ============================================================================
# Topology A (All-on-VPS) Setup Script
# Canvas Core Workspace — Full Deployment Automation
#
# Usage:
#   chmod +x scripts/setup-topology-a.sh
#   ./scripts/setup-topology-a.sh
#
# This script:
#   1. Installs Node.js 20+ and pnpm (if missing)
#   2. Installs all workspace dependencies
#   3. Builds all packages for production
#   4. Installs and configures PM2 for service management
#   5. Starts canvas-gateway (port 3001) and canvas-frontend (port 5173)
#   6. Configures PM2 startup to survive reboots
# ============================================================================

set -euo pipefail

# --- Configuration ---
WORKSPACE_ROOT="${WORKSPACE_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
GATEWAY_PORT="${PORT:-3001}"
FRONTEND_PORT="${FRONTEND_PORT:-5173}"
NODE_MIN_VERSION=20
LOG_DIR="${WORKSPACE_ROOT}/logs"
DATA_DIR="${WORKSPACE_ROOT}/server/data"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# --- Pre-flight checks ---
echo ""
echo "============================================"
echo "  Canvas Core — Topology A Setup"
echo "  All-on-VPS Deployment"
echo "============================================"
echo ""
log_info "Workspace root: ${WORKSPACE_ROOT}"
log_info "Gateway port:   ${GATEWAY_PORT}"
log_info "Frontend port:  ${FRONTEND_PORT}"
echo ""

# --- Step 1: Install Node.js 20+ ---
log_info "Step 1/6: Checking Node.js installation..."

install_node() {
  log_info "Installing Node.js 20.x via NodeSource..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  sudo apt-get install -y nodejs
  log_ok "Node.js installed: $(node --version)"
}

if command -v node &>/dev/null; then
  NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
  if [ "$NODE_VERSION" -ge "$NODE_MIN_VERSION" ]; then
    log_ok "Node.js $(node -v) is already installed (>= ${NODE_MIN_VERSION})"
  else
    log_warn "Node.js $(node -v) is too old. Installing v20+..."
    install_node
  fi
else
  install_node
fi

# --- Step 2: Install pnpm ---
log_info "Step 2/6: Checking pnpm installation..."

if command -v pnpm &>/dev/null; then
  log_ok "pnpm $(pnpm --version) is already installed"
else
  log_info "Installing pnpm via npm..."
  npm install -g pnpm
  log_ok "pnpm installed: $(pnpm --version)"
fi

# --- Step 3: Install dependencies and build ---
log_info "Step 3/6: Installing dependencies and building packages..."

cd "$WORKSPACE_ROOT"

# Create required directories
mkdir -p "$LOG_DIR" "$DATA_DIR"

# Install dependencies
log_info "Running pnpm install..."
pnpm install --frozen-lockfile 2>/dev/null || pnpm install
log_ok "Dependencies installed"

# Build all packages
log_info "Building all packages..."
pnpm build 2>&1 | while read -r line; do echo "  $line"; done
log_ok "All packages built successfully"

# Verify build outputs
if [ -f "${WORKSPACE_ROOT}/server/dist/index.js" ]; then
  log_ok "Gateway server build verified"
else
  log_error "Gateway server build failed — server/dist/index.js not found"
  exit 1
fi

if [ -d "${WORKSPACE_ROOT}/apps/web-canvas/dist" ]; then
  log_ok "Canvas frontend build verified"
else
  log_warn "Canvas frontend dist not found — will use Vite preview mode"
fi

# --- Step 4: Install PM2 ---
log_info "Step 4/6: Installing PM2 process manager..."

if command -v pm2 &>/dev/null; then
  log_ok "PM2 $(pm2 --version) is already installed"
else
  sudo npm install -g pm2
  log_ok "PM2 installed: $(pm2 --version)"
fi

# --- Step 5: Generate environment file ---
log_info "Step 5/6: Generating environment configuration..."

ENV_FILE="${WORKSPACE_ROOT}/.env"
if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" << EOF
# Canvas Core Workspace — Topology A Environment
# Generated by setup-topology-a.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Gateway Server
PORT=${GATEWAY_PORT}
HOST=0.0.0.0
NODE_ENV=production

# Frontend
FRONTEND_PORT=${FRONTEND_PORT}
VITE_GATEWAY_URL=ws://localhost:${GATEWAY_PORT}
VITE_API_URL=http://localhost:${GATEWAY_PORT}

# Database
DB_PATH=./data/canvas.json

# Hermes / Eva Integration
HERMES_API_BASE=http://localhost:8080/v1
WORKSPACE_ROOT=${WORKSPACE_ROOT}
EOF
  log_ok "Environment file created at ${ENV_FILE}"
else
  log_warn "Environment file already exists — skipping"
fi

# Generate Hermes config
log_info "Generating Hermes/Eva integration configs..."
HERMES_YAML="${WORKSPACE_ROOT}/config/hermes-canvas.yaml"
HERMES_JSON="${WORKSPACE_ROOT}/config/hermes-canvas.json"
mkdir -p "${WORKSPACE_ROOT}/config"

cat > "$HERMES_YAML" << EOF
# Canvas Workspace MCP Configuration for Hermes/Eva
# Generated by setup-topology-a.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Paste this into your Hermes config.yaml under mcp_servers:

mcp_servers:
  canvas_workspace:
    url: "http://localhost:${GATEWAY_PORT}/mcp"
    transport: "http"
  skybridge_tools:
    command: "node"
    args: ["${WORKSPACE_ROOT}/apps/skybridge-mcp/dist/server/index.js"]

# Canvas Gateway endpoints (for direct API access)
canvas_gateway:
  url: "http://localhost:${GATEWAY_PORT}"
  ws_url: "ws://localhost:${GATEWAY_PORT}/ws"
  mcp_http_url: "http://localhost:${GATEWAY_PORT}/mcp"
  mcp_sse_url: "http://localhost:${GATEWAY_PORT}/sse"
EOF

cat > "$HERMES_JSON" << EOF
{
  "mcp_servers": {
    "canvas_workspace": {
      "name": "canvas_workspace",
      "transport": "http",
      "url": "http://localhost:${GATEWAY_PORT}/mcp"
    },
    "skybridge_tools": {
      "name": "skybridge_tools",
      "transport": "stdio",
      "command": "node",
      "args": ["${WORKSPACE_ROOT}/apps/skybridge-mcp/dist/server/index.js"]
    }
  },
  "canvas_gateway": {
    "url": "http://localhost:${GATEWAY_PORT}",
    "ws_url": "ws://localhost:${GATEWAY_PORT}/ws",
    "mcp_http_url": "http://localhost:${GATEWAY_PORT}/mcp",
    "mcp_sse_url": "http://localhost:${GATEWAY_PORT}/sse"
  }
}
EOF

log_ok "Hermes config (YAML): ${HERMES_YAML}"
log_ok "Hermes config (JSON): ${HERMES_JSON}"

# --- Step 6: Start services with PM2 ---
log_info "Step 6/6: Starting services with PM2..."

# Stop any existing instances
pm2 delete canvas-gateway 2>/dev/null || true
pm2 delete canvas-frontend 2>/dev/null || true

# Start services using pm2.config.js
pm2 start "${WORKSPACE_ROOT}/pm2.config.js"

# Save PM2 process list
pm2 save

# Setup PM2 startup script for boot persistence
log_info "Configuring PM2 startup for reboot persistence..."
STARTUP_CMD=$(pm2 startup 2>&1 | grep -oP 'sudo .*' | head -1) || true
if [ -n "$STARTUP_CMD" ]; then
  log_warn "Run this command to enable PM2 startup:"
  echo "  ${STARTUP_CMD}"
else
  log_ok "PM2 startup already configured"
fi

echo ""
echo "============================================"
echo "  ✅ Topology A Setup Complete!"
echo "============================================"
echo ""
echo "  Services running:"
echo "    • canvas-gateway   → http://0.0.0.0:${GATEWAY_PORT}"
echo "    • canvas-frontend  → http://0.0.0.0:${FRONTEND_PORT}"
echo ""
echo "  MCP Endpoints:"
echo "    • HTTP: http://localhost:${GATEWAY_PORT}/mcp"
echo "    • SSE:  http://localhost:${GATEWAY_PORT}/sse"
echo "    • WS:   ws://localhost:${GATEWAY_PORT}/ws"
echo ""
echo "  Hermes/Eva configs:"
echo "    • YAML: ${HERMES_YAML}"
echo "    • JSON: ${HERMES_JSON}"
echo ""
echo "  Open in browser:"
echo "    → http://$(hostname -I | awk '{print $1}' 2>/dev/null || echo '<YOUR_VPS_IP>'):${FRONTEND_PORT}"
echo ""
echo "  PM2 commands:"
echo "    pm2 status          — View service status"
echo "    pm2 logs            — View all logs"
echo "    pm2 restart all     — Restart all services"
echo "    pm2 monit           — Real-time monitoring"
echo ""
echo "============================================"
